# CMake generated Testfile for 
# Source directory: /home/qijing/eRPC
# Build directory: /home/qijing/eRPC
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(create_session_test "/home/qijing/eRPC/build/create_session_test")
set_tests_properties(create_session_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;425;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(destroy_session_test "/home/qijing/eRPC/build/destroy_session_test")
set_tests_properties(destroy_session_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;425;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(small_msg_test "/home/qijing/eRPC/build/small_msg_test")
set_tests_properties(small_msg_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;425;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(large_msg_test "/home/qijing/eRPC/build/large_msg_test")
set_tests_properties(large_msg_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;425;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(req_in_cont_func_test "/home/qijing/eRPC/build/req_in_cont_func_test")
set_tests_properties(req_in_cont_func_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;425;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(req_in_req_func_test "/home/qijing/eRPC/build/req_in_req_func_test")
set_tests_properties(req_in_req_func_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;425;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(packet_loss_test "/home/qijing/eRPC/build/packet_loss_test")
set_tests_properties(packet_loss_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;425;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(multi_process_test "/home/qijing/eRPC/build/multi_process_test")
set_tests_properties(multi_process_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;425;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(rpc_sm_test "/home/qijing/eRPC/build/rpc_sm_test")
set_tests_properties(rpc_sm_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;440;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(rpc_list_test "/home/qijing/eRPC/build/rpc_list_test")
set_tests_properties(rpc_list_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;440;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(rpc_req_test "/home/qijing/eRPC/build/rpc_req_test")
set_tests_properties(rpc_req_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;440;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(rpc_resp_test "/home/qijing/eRPC/build/rpc_resp_test")
set_tests_properties(rpc_resp_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;440;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(rpc_cr_test "/home/qijing/eRPC/build/rpc_cr_test")
set_tests_properties(rpc_cr_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;440;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(rpc_rfr_test "/home/qijing/eRPC/build/rpc_rfr_test")
set_tests_properties(rpc_rfr_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;440;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(rpc_kick_test "/home/qijing/eRPC/build/rpc_kick_test")
set_tests_properties(rpc_kick_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;440;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
add_test(dpdk_ownership_memzone_test "/home/qijing/eRPC/build/dpdk_ownership_memzone_test")
set_tests_properties(dpdk_ownership_memzone_test PROPERTIES  _BACKTRACE_TRIPLES "/home/qijing/eRPC/CMakeLists.txt;456;add_test;/home/qijing/eRPC/CMakeLists.txt;0;")
subdirs("third_party/HdrHistogram_c")
subdirs("third_party/googletest")
subdirs("third_party/gflags")
